### ISSUE TITLE
Convenience Methods don't work

### ISSUE THREAD

**Issue by bkkrishna** [voku/php-domain-parser#4]
Hi there!

I tried to use this with Laravel 5.5 but the [Convenience Methods](https://github.com/voku/php-domain-parser#convenience-methods) don't actually work giving me an error while traversing through the host property saying that it is protected.

`$publicSuffix = $url->host->publicSuffix;` 

So, basically, I can't access it like that. Have I missed something here?

Thanks!

**Comment by voku** [comment]
Sorry the doc wasn't up to date... please use "host->getPublicSuffix()" this is much cleaner, because magic getter and setter are not very helpful for readability, auto-completion and static analyses. 

-> https://github.com/voku/php-domain-parser/commit/da0b4ee2b5984065f633d129314ef2dd5fed5233#diff-04c6e90faac2675aa89e2176d2eec7d8R120

**Comment by bkkrishna** [comment]
Thanks for the reply @voku. But no matter how hard I try, I cannot access the **$host** property(or any other properties of the **$url** object) or it's sub-properties giving me an error of protected visibility.

The only thing I get to work here is  
`$parser->getPublicSuffix('www.scottwills.co.uk')` . 
But my use case needs me to be able to access almost all the proterties of $url object. 

Kindly help.

**Comment by voku** [comment]
Hi, please take a look at the tests, there are good working examples. 
https://github.com/voku/php-domain-parser
PS: I think there are also getter for the host property. And do you use a IDE with auto-completion? If not try PhpStorm: https://www.jetbrains.com/phpstorm/eap/
Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: B K Krishna Magar <notifications@github.com> 
Datum: 20.03.18  04:24  (GMT+01:00) 
An: voku/php-domain-parser <php-domain-parser@noreply.github.com> 
Cc: Lars Moelleken <voku@voku-online.de>, Mention <mention@noreply.github.com> 
Betreff: Re: [voku/php-domain-parser] Convenience methods doesn't work (#4) 

Thanks for the reply @voku. But no matter how hard I try, I cannot access the $host property(or any other properties of the $url object) or it's sub-properties giving me an error of protected visibility.
The only thing I get to work here is

$parser->getPublicSuffix('www.scottwills.co.uk') .

But my use case needs me to be able to access almost all the proterties of $url object.
Kindly help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/voku/php-domain-parser","title":"voku/php-domain-parser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/voku/php-domain-parser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bkkrishna in #4: Thanks for the reply @voku. But no matter how hard I try, I cannot access the **$host** property(or any other properties of the **$url** object) or it's sub-properties giving me an error of protected visibility.\r\n\r\nThe only thing I get to work here is  \r\n`$parser-\u003egetPublicSuffix('www.scottwills.co.uk')` . \r\nBut my use case needs me to be able to access almost all the proterties of $url object. \r\n\r\nKindly help.  "}],"action":{"name":"View Issue","url":"https://github.com/voku/php-domain-parser/issues/4#issuecomment-374460636"}}}

**Comment by bkkrishna** [comment]
Hello again!
I always use PHPStorm but something's missing in your codebase, I guess, that is still preventing the Convenience methods to work.

While I went through your test cases, I got `toArray()` method that could let me access the protected properties in a single go like the following : 
`$urlProperties = $url->toArray();`
I got it working this way which fulfills my needs at this point.

Thank you anyway!
